apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: otel-collector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
        - name: otel-collector
          image: otel/opentelemetry-collector-contrib:0.102.1
          args:
            - --config=/etc/otel/collector.yaml
          ports:
            - name: otlp-http
              containerPort: 4318
            - name: prom-metrics
              containerPort: 9464
          volumeMounts:
            - name: config
              mountPath: /etc/otel
            - name: auth
              mountPath: /etc/otel/auth
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 300m
              memory: 256Mi
      volumes:
        - name: config
          configMap:
            name: otel-collector-config
            items:
              - key: collector.yaml
                path: collector.yaml
        - name: auth
          secret:
            secretName: otel-collector-basic-auth
