apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: uptime-kuma
resources:
  - namespace.yaml
  - pvc-lhowsam.yaml
  - pvc-foam.yaml
  - lhowsam.yaml
  - foam.yaml
  - lhowsam-service.yaml
  - foam-service.yaml
  - ingress-lhowsam.yaml
  - ingress-foam.yaml
