apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-foam-pvc
  namespace: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
