{
 "title": "Cloudflare Workers",
 "tags": [
  "cloudflare",
  "workers"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Worker requests / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_worker_requests_count[5m])) by (script_name)",
     "legendFormat": "{{script_name}}"
    }
   ]
  },
  {
   "title": "Worker errors / second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(cloudflare_worker_errors_count[5m])) by (script_name)",
     "legendFormat": "{{script_name}}"
    }
   ]
  },
  {
   "title": "Wall duration P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "max(cloudflare_worker_duration{quantile=\"P99\"}) by (script_name)",
     "legendFormat": "{{script_name}}"
    }
   ]
  },
  {
   "title": "CPU time P99",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "max(cloudflare_worker_cpu_time{quantile=\"P99\"}) by (script_name)",
     "legendFormat": "{{script_name}}"
    }
   ]
  }
 ]
}